### ISSUE TITLE
Unable to call procedures with decimals in their name

### ISSUE THREAD

**Issue by jkirsons** [SAP-samples/hana-hdbext-promisfied-example#16]
When loading/calling a procedure with characters like decimals such as:
company.project_db.procedures::proc_RUN_L0

The procedure needs to be in double quotes for the CALL statement to succeed,
however the call to fetchSPMetadata needs the procedure to not have double quotes for it to be able to find the procedure to get it's parameters.

Can you change this line:
https://github.com/SAP-samples/hana-hdbext-promisfied-example/blob/fccf5bae488f7b964f5625fa761bfa55184236ce/hdb/index.js#L270

to:
return this.preparePromisified(`CALL ${schema}."${procedure}"(${callString})`)

placing double quotes around the procedure name?

**Comment by jung-thomas** [comment]
Thanks for the report and the solution. I've integrated this fix, tested and pushed it to npm.
