### ISSUE TITLE
sap-hdbext-promisfied dependent on vulnerable version of @sap/hana-client

### ISSUE THREAD

**Issue by borge97** [SAP-samples/hana-hdbext-promisfied-example#18]
Hi,

the "npm audit" is currently failing in our repo.

------------------------------------------------------------------
@sap/hana-client  <=2.21.28
Severity: moderate
SAP HANA Node.js client package vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-6339-gv7w-g5f4
fix available via `npm audit fix`
node_modules/sap-hdbext-promisfied/node_modules/@sap/hdbext/node_modules/@sap/hana-client
------------------------------------------------------------------

The problem is that @sap/hdbext is fixed to version 8.0.6 in the hdbext/npm-shrinkwrap.json:

└─┬ sap-hdbext-promisfied@2.202407.1
  └─┬ @sap/hdbext@8.0.6
    └── @sap/hana-client@2.21.28

Therefore, we cannot fix it manually with "overrides". Are there plans to upgrade @sap/hdbext to the latest version (8.0.8). This would fix @sap/hana-client (transitively).

Best regards
Alex

**Comment by jung-thomas** [comment]
Update all dependencies and published new version to NPM.
