### ISSUE TITLE
[Error] Could not create temporary table: invalid column name: 0

### ISSUE THREAD

**Issue by sahilkumar129** [SAP-samples/hana-hdbext-promisfied-example#3]
Hi,

I have a procedure that has only one input parameter that is a table. And I am passing the input parameter as show below:
![image](https://user-images.githubusercontent.com/21966268/93850432-b85ec280-fccb-11ea-8d3f-6fb9a7346743.png)

Then, calling `callProcedurePromisified` throws an error `invalid column name`.

I checked the issue and it is occuring in `wrap-params` file in below function.
![image](https://user-images.githubusercontent.com/21966268/93850587-070c5c80-fccc-11ea-9caf-48ad612a4933.png)
 
It is returning false which causes the params to go in wrong format and it throws an error during insertion in the temporary table. This works fine with more than 1 parameter.

Procedure definition:

```sql
PROCEDURE "zp_get_execution_ids"(
	IN PLAN_IDS TABLE(PLAN_ID BIGINT),
	OUT RESULT TABLE(PLAN_ID BIGINT, EXECUTION_ID BIGINT)
) 
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
READS SQL DATA
AS
BEGIN

RESULT = SELECT PLAN_ID, 1 AS EXECUTION_ID 
        FROM :PLAN_IDS;

END;
```

API Call
```js
app.get("/checkProc", async (req, res) => {
	try {
		const DbClass = require("sap-hdbext-promisfied");

		const db = new DbClass(req.db);
		const loadProcedure = await db.loadProcedurePromisified(hdbext, null, "zp_get_execution_ids");
		const params = [{
			"PLAN_ID": 49284
		}, {
			"PLAN_ID": 49304
		}, {
			"PLAN_ID": 49305
		}];
		const storedProc = await db.callProcedurePromisified(loadProcedure, [params]);
		const results = storedProc.outputScalar;

		return results;
	} catch (err) {
		console.error(err.message);
	}
});
```

Is there something that I am doing wrong or is it a bug?

**Comment by jung-thomas** [comment]
Well first I think you are actually discussing something that occurs not in this module but in the standard @sap/hdbext.  This module just adds a Promisified wrapper and few other utilities around @sap/hdbext.  But the check you are referring to is in the standard module. 

That said I do believe you are calling it wrong. The input JSON needs to list all the parameters at the first level.  You don't have an element in your JSON for PLAN_IDS.  You need PLAN_IDS that in turn is an object with the individual records.

**Comment by sahilkumar129** [comment]
Thanks for the quick reply but I am still not clear about it. So, if I understand correctly we have 2 cases:
1. Only one input param which is table: In that case, we pass input parameter as array of items of that table i.e. in this case
```json
[{
	"PLAN_ID": 49284
	}, {
	"PLAN_ID": 49304
	}, {
	"PLAN_ID": 49305
}];
```

2. All other cases: we pass array of all parameters. Example

```js
[ 
    1, 
    "abc", 
    [{
        "PLAN_ID": 49284
    },{
        "PLAN_ID": 49304
    },{
        "PLAN_ID": 49305
    }]
];
```
If this is the case, then it is working fine.

In case, this is not the right platform to discuss this issue can you tell me where can I create the issue for @sap/hdbext?

**Comment by jung-thomas** [comment]
I think I might see your error. You are creating params as an array:
``` JavaScript
const params = [{
			"PLAN_ID": 49284
		}, {
			"PLAN_ID": 49304
		}, {
			"PLAN_ID": 49305
		}];
```

But then you are passing it into the procedure call within another array:

`		const storedProc = await db.callProcedurePromisified(loadProcedure, [params]);`


Look at the example from the @sap/hdbext help:
https://www.npmjs.com/package/@sap/hdbext#loadprocedureclient-schemaname-procedurename-callback
```JavaScript
hdbext.loadProcedure(client, null, 'getCustomers', function (err, sp) {
  if (err) {
    return console.error(err);
  }
 
  sp([
    { ID: 1, NAME: 'Alex' },
    { ID: 2, NAME: 'Peter' }
  ], function (err, parameters, tableRows) {
    if (err) {
      return console.error(err);
    }
 
    console.log(parameters);
    console.log(tableRows);
  });
});
```

So if you are going to create params as an array, don't also put it in an array.  Have you tried just calling it as 
`		const storedProc = await db.callProcedurePromisified(loadProcedure, params);`

**Comment by sahilkumar129** [comment]
Yes, it works that way. But in case there are more params, say for example another table or parameter input, then it has to be sent in an array. 
Previously, I generalized the input but it seems that is not the case. So, I have updated my logic to send the params without array if there is one single table input and in other cases as array of all input parameters. It works fine that way.
