### ISSUE TITLE
Prepared statements on JSONCollections tables

### ISSUE THREAD

**Issue by fidsusj** [SAP-samples/hana-hdbext-promisfied-example#4]
Hey Thomas,

I am trying to prepare a SELECT statement using your promisfied hdbext library. Instead of a SELECT on a classic column table I'm trying to read from a JSONCollection in the HANA document store like this:

`const statement = await db.preparePromisified("SELECT * FROM CollectionTable WHERE "itemkey"=? ORDER BY timestamp DESC LIMIT 1");
`
I am receiving the error message: "feature not supported: WHERE clause with unsupported expressions on collection tables"

Will this feature be added in near future or should I switch to normal column tables instead? Thanks a lot.

**Comment by jung-thomas** [comment]
You are getting that message from HANA itself not from my little wrapper around the client library. I couldn't comment on the support plans for this specific feature in HANA itself. That's way outside the scope of this helper utility.
